pnr_data_file = 'Dataset/passenger_pnr_dataset.csv'
flight_data_file = 'Dataset/flight_schedule_dataset.csv'
test_PNR_data_file = 'Dataset/Mphasis_Processed/Mock_PNR_Booking.csv'
test_flight_data_file = 'Dataset/Mphasis_Processed/Mock_Flight_Inv.csv'
airport_code_location_data_file = 'Dataset/airport-code-to-location.csv'
# test_PNR_data_file = 'Dataset/test_data/PNR_Test.csv'
# test_flight_data_file = 'Dataset/test_data/flight_test.csv'
n_cabin=2
ETD=72
cabinScoreFirst=1950
cabinScoreBusiness=1800
cabinScorePremium=1700
cabinScoreEconomy=1592
MCT=1
MAXCT=12
PNR_SSR={'grade1':250,'grade2':150}
loyalty={'CM':2000,'Platinum':1800,'Gold':1600,'Silver':1500}
PNR_connection=100
PNR_paidservice=200
PNR_bookingtype=500
PNR_pax=50
NON_ASSIGNMENT_COST=100
CITY_PAIR_THRESHOLD=8
weight_flight_map=100
weight_pnr_map=100
weight_cabin_map=100
