pnr_data_file = 'Dataset/passenger_pnr_dataset.csv'
flight_data_file = 'Dataset/flight_schedule_dataset.csv'
test_PNR_data_file = 'Dataset/Mphasis_Processed/Mock_PNR_Booking.csv'
test_flight_data_file = 'Dataset/Mphasis_Processed/Mock_Flight_Inv.csv'
airport_code_location_data_file = 'Dataset/airport-code-to-location.csv'
# test_PNR_data_file = 'Dataset/test_data/PNR_Test.csv'
# test_flight_data_file = 'Dataset/test_data/flight_test.csv'
weight_flight_map = 100
weight_pnr_map = 100
weight_cabin_map = 100
pnr_normalize_factor = 100
flight_normalize_factor = 100
cabin_normalize_factor = 100
NON_ASSIGNMENT_COST=100
all_flights = {}
pnr_objects = {}
pnr_flight_mapping = {}
pnr_to_s2 = {}